site_name: SINGD
site_url: https://https://readthedocs.org/projects/singd/
repo_url: https://github.com/f-dangel/singd/
repo_name: f-dangel/singd
site_author: Wu Lin, Runa Eschenhagen, Felix Dangel, Agustinus Kristiadi, Kirill Neklyudov, Richard Turner, Alireza Makhzani
watch:
  - singd
nav:
    - Getting Started: index.md
    - Code Examples: generated/gallery
    - API Documentation: api.md
    - Developer Notes: develop.md
    - Internal:
      - Structures: structures.md
      - Templates: templates.md
      - Interface: interface.md
theme:
    name: material
    features:
        - content.code.copy
copyright: Copyright &copy; 2023 Wu Lin, Runa Eschenhagen, Felix Dangel, Agustinus Kristiadi, Kirill Neklyudov, Richard Turner, Alireza Makhzani
markdown_extensions:
    - pymdownx.arithmatex: # LaTeX math
          generic: true
    - pymdownx.highlight: # code highlighting
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite # code highlighting
    - pymdownx.snippets # code highlighting
    - pymdownx.superfences # code highlighting
    - footnotes
plugins:
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                      show_root_heading: true
                      show_source: true
                      show_bases: true
                      show_signature_annotations: true
                      separate_signature: true
                      docstring_section_style: list
                      merge_init_into_class: true
    - gallery:
          conf_script: docs/gallery_conf.py
          examples_dirs: docs/examples
          gallery_dirs: docs/generated/gallery
          matplotlib_animations: true
    - search
extra_javascript:
    - javascripts/mathjax.js # LaTeX math
    - https://polyfill.io/v3/polyfill.min.js?features=es6 # LaTeX math
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # LaTeX math
