name: Lint-isort

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-lint
    - name: Run isort
      run: |
        make isort-check
